name: jormungand
favicon: null
layout_spectrum: 0.83833
typography_spectrum: 0.58862
title: Jeremy Chinn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#000000'
    - '#fefefe'
    - '#807d73'
    - '#c6c6bc'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
